# Generated by Django 2.1.5 on 2020-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=11)),
                ('number2', models.CharField(max_length=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('check', models.CharField(default='FALSE', max_length=10)),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
