# Generated by Django 2.1.5 on 2020-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='sex',
        ),
        migrations.AddField(
            model_name='visitor',
            name='image',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
