# Generated by Django 2.1.5 on 2020-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_data', '0002_auto_20200624_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='check',
            field=models.CharField(default='FALSE', max_length=10),
        ),
    ]
