# Generated by Django 2.1.5 on 2020-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_data', '0004_auto_20200627_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
